# Generated by Django 4.2.6 on 2023-10-31 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_answer_delete_incorrectanswers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='module',
            name='number_of_completed_tests',
        ),
        migrations.RemoveField(
            model_name='module',
            name='number_of_tasks',
        ),
        migrations.RemoveField(
            model_name='task',
            name='correct_answer',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='theory_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='theory_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AlterField(
            model_name='module',
            name='number_of_completed_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='module',
            name='number_of_tests',
            field=models.IntegerField(default=-1),
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
