# Generated by Django 4.2.6 on 2023-12-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_course_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number_of_completed_lessons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='number_of_completed_tests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='number_of_lessons',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='number_of_tests',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='number_of_completed_lessons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='number_of_lessons',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
