# Generated by Django 4.2.6 on 2023-12-15 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_course_number_of_completed_lessons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='img_course/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'svg', 'jpg'])]),
        ),
    ]
