# Generated by Django 4.2.6 on 2023-12-15 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_alter_course_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='answers',
            field=models.ManyToManyField(related_name='tasks', to='myapi.answer'),
        ),
        migrations.AddField(
            model_name='test',
            name='tasks',
            field=models.ManyToManyField(related_name='tests', to='myapi.task'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
