# Generated by Django 4.2.6 on 2023-12-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_task_answers_test_tasks_alter_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='answers',
            field=models.ManyToManyField(null=True, related_name='tasks', to='myapi.answer'),
        ),
        migrations.AlterField(
            model_name='test',
            name='tasks',
            field=models.ManyToManyField(null=True, related_name='tests', to='myapi.task'),
        ),
    ]
