# Generated by Django 4.2.6 on 2023-12-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_alter_task_answers_alter_test_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='tasks',
            field=models.ManyToManyField(related_name='tests', to='myapi.task'),
        ),
    ]
