# Generated by Django 4.2.6 on 2023-12-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_alter_test_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='test',
            name='tasks',
        ),
    ]
